return {
    { "folke/flash.nvim",                            enabled = true },
    { "hrsh7th/cmp-path",                            enabled = true },
    { "folke/lazy.nvim",                             enabled = true },
    { "nvim-lua/plenary.nvim",                       enabled = true },
    { "williamboman/mason.nvim",                     enabled = true },
    { "rebelot/kanagawa.nvim",                       enabled = true },
    { "williamboman/mason-lspconfig.nvim",           enabled = true },
    { "ThePrimeagen/harpoon",                        enabled = true },
    { "stevearc/oil.nvim",                           enabled = true },
    { "hrsh7th/nvim-cmp",                            enabled = true },
    { "nvim-treesitter/nvim-treesitter-textobjects", enabled = true },
    { "hrsh7th/cmp-nvim-lsp",                        enabled = true },
    { "neovim/nvim-lspconfig",                       enabled = true },
    { "Exafunction/codeium.vim",                     enabled = true },
    { "hrsh7th/cmp-buffer",                          enabled = true },
    { "folke/neodev.nvim",                           enabled = true },
    { "nvim-treesitter/nvim-treesitter",             enabled = true },
    { "nvim-telescope/telescope.nvim",               enabled = true },
    { "nvim-tree/nvim-web-devicons",                 enabled = true },
}
